[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = ""
healthcheckPath = "/api/owner"
healthcheckPort = 80
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[deploy.env]
NODE_ENV = "production"
PORT = "3001"
